<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "phototheque_vmrtamsdraal"
 *
 * Auto generated by Extension Builder 2021-06-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Photothèque VMRTAMSBRAAL',
    'description' => 'projet de photothèque DAWIN 2020-2021',
    'category' => 'plugin',
    'author' => 'Valentin MOREL, Romain TALON, Simon BOTTE, Axel MORICEAU, ROMAIN ANGIER, Lauranne APERS',
    'author_email' => 'valentin.morel1@etu.u-bordeaux.fr, romain.talon@etu.u-bordeaux.fr, simon.botte@etu.u-bordeaux.fr, axel.moriceau@etu.u-bordeaux.fr, romain.angier@etu.u-bordeaux.fr, lauranne.apers@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
